<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Prospect;

class ProspectController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $data = Prospect::with('user')->orderByDesc('id')->paginate(15);
     
        return view('prospect.list',
            ['data'=>$data]
        );
    }
    public function register(){
        return view('prospect.register',
            [
                'states' => self::getStates(),
                'comercialBusiness' => self::getComercialBusiness() ,
                'cities' => self::getCities()
            ]
        );
    }
    public function edit($id){

        $data = Prospect::find($id);

        return view('prospect.edit',
            [
                'data' => $data ,
                'states' => self::getStates(),
                'comercialBusiness' => self::getComercialBusiness() ,
                'cities' => self::getCities()
            ]
        );
    }
    public function store(Request $request){
        $this->validate($request, [
            'name' => 'required|max:255' ,
            'email' => ['required_without:phone','max:255'] ,
            'phone' => ['required_without:email','max:255'] ,
        ]);

        $new = new Prospect;
        
        $new->name = $request->name;
        $new->phone = $request->phone;
        $new->email = $request->email;
        $new->company_name = $request->company_name;
        $new->address = $request->address;
        $new->country = $request->country;
        $new->estate = $request->estate;
        $new->city = $request->city;
        $new->commercial_business = $request->commercial_business;
        $new->observations = $request->observations;
        $new->user_id = $request->user()->id;

        if($new->save()){
            return redirect()->back()->withSuccess('Información guardada correctamente'); 
        }
        return redirect()->back()->withErrors(['Error' => 'Problema al almacenar datos']);     

    }
    public function update(Request $request){
        
    }    
    public function getStates(){
        return [
            'Aguascalientes' ,
            'Baja California' ,
            'Baja California Sur' ,
            'Campeche' ,
            'Chiapas' ,
            'Chihuahua' ,
            'Ciudad de México' ,
            'Coahuila' ,
            'Colima' ,
            'Durango' ,
            'Guanajuato' ,
            'Guerrero' ,
            'Hidalgo' ,
            'Jalisco' ,
            'México' ,
            'Michoacán' ,
            'Morelos' ,
            'Nayarit' ,
            'Nuevo León' ,
            'Oaxaca' ,
            'Puebla' ,
            'Querétaro' ,
            'Quintana Roo' ,
            'San Luis Potosí' ,
            'Sinaloa' ,
            'Sonora' ,
            'Tabasco' ,
            'Tamaulipas' ,
            'Tlaxcala' ,
            'Veracruz' ,
            'Yucatán' ,
            'Zacatecas' ,
        ];
    }
    public function getComercialBusiness()
    {
        return [
            'ABARROTES' ,
            'ACADEMIA DE ACTIVIDADES DEPORTIVAS Y DE ESPARCIMIENTO' ,
            'ACADEMIA DE ACTIVIDADES TÉCNICAS Y DE CAPACITACIÓN' ,
            'ACADEMIA DE NATACION' ,
            'ACCESORIOS AUTOMOTRICES' ,
            'ACCESORIOS DE VESTIR' ,
            'ACCESORIOS FOTOGRAFICOS' ,
            'ACCESORIOS PARA SEGURIDAD INDUSTRIAL Y DOMESTICA' ,
            'ACCESORIOS RELACIONADOS' ,
            'ACCESORIOS RELACIONADOS CON EL GIRO' ,
            'ACCESORIOS Y AUTOPARTES SEMINUEVAS' ,
            'ACEITES Y LUBRICANTES' ,
            'ACOMODADORES DE AUTOS EVENTUAL' ,
            'ACTIVIDADES DEPORTIVAS Y DE ESPARCIMIENTO' ,
            'ACTIVIDADES EXTRACTIVAS' ,
            'ACUARIO' ,
            'ADIESTRAMIENTO DE CANINOS' ,
            'ADITIVOS' ,
            'AFILADURIA' ,
            'AGEN. DE AUTOS NUEVOS' ,
            'AGEN. DE AUTOS SEMINUEVOS' ,
            'AGEN. DE AUTOTRANSPORTES' ,
            'AGEN. DE PUBLICIDAD' ,
            'AGENCIA DE MENSAJERIA Y PAQUETERIA' ,
            'AGENCIA DE MOTOCICLETAS' ,
            'AGENCIA DE VIAJES' ,
            'AGENCIAS NOTICIOSAS' ,
            'ALBERGUE' ,
            'ALFOMBRAS' ,
            'ALIMENTOS' ,
            'ALIMENTOS CON VINOS GENEROSOS' ,
            'ALIMENTOS PARA CONSUMO INMEDIATO' ,
            'ALIMENTOS PARA LLEVAR' ,
            'ALIMENTOS PARA USO ANIMAL' ,
            'ALMACEN' ,
            'ALQUILER DE APARATOS ELECTRICOS Y ELECTRONICOS' ,
            'ALQUILER DE ART. DE OFICINA' ,
            'ALQUILER DE AUTOMOVILES CON CHOFER' ,
            'ALQUILER DE ROPA' ,
            'ALQUILER SIN INTERMEDIACION DE OFICINAS Y LOCALES COMERCIALES' ,
            'ALQUILER SIN INTERMEDIACION DE VIVIENDAS AMUEBLADAS' ,
            'ALQUILER SIN INTERMEDIACION DE VIVIENDAS NO AMUEBLADAS' ,
            'ALUMINIO' ,
            'ANIMALES' ,
            'ANTIGUEDADES' ,
            'ANUNCIO CARTELERA DE AZOTEA' ,
            'ANUNCIO CARTELERA DE PISO' ,
            'ANUNCIO EN BAÑO PUBLICO' ,
            'ANUNCIO EN CASETA TELEFONICA' ,
            'ANUNCIO EN PARADERO DE TRANSPORTE PUBLICO' ,
            'ANUNCIO EN PUESTO DE PERIODICO' ,
            'ANUNCIO ESTRUCTURAL' ,
            'ANUNCIO ESTRUCTURAL SOBRE PUENTE PEATONAL' ,
            'ANUNCIO EVENTUAL EN CARTELES IMPRESOS EN TABLEROS DEL AYUNTAMIENTO' ,
            'ANUNCIO EVENTUAL EN VALLA' ,
            'ANUNCIO EVENTUAL INFLABLE' ,
            'ANUNCIO EVENTUAL MANTA' ,
            'ANUNCIO EVENTUAL PENDON' ,
            'ANUNCIO SEMIESTRUCTURAL LUMINOSO' ,
            'ANUNCIO SEMIESTRUCTURAL OPACO' ,
            'ANUNCIO SIN ESTRUCTURA LUMINOSO' ,
            'ANUNCIO SIN ESTRUCTURA OPACO' ,
            'ANUNCIOS EN PUESTOS DE FLORES' ,
            'ANUNCIOS ESPECIALES' ,
            'APARATO MUSICAL' ,
            'APARATOS ELECTRODOMESTICOS' ,
            'APARATOS ELECTRONICOS' ,
            'APARATOS ORTOPEDICOS' ,
            'APARATOS Y ACCESORIOS MUSICALES' ,
            'ARRENDAMIENTO DE MAQUINARIA' ,
            'ART. DE BELLEZA' ,
            'ART. DE DECORACION' ,
            'ART. DE JARDINERIA' ,
            'ART. DE LIMPIEZA' ,
            'ART. DE PIEL' ,
            'ART. NAVIDEÑOS' ,
            'ART. PARA FIESTA' ,
            'ART. PROMOCIONALES' ,
            'ARTESANIAS' ,
            'ARTICULOS DEPORTIVOS' ,
            'ARTICULOS PARA ALBERCA' ,
            'ARTICULOS PARA DISEÑO Y PINTURA' ,
            'ARTICULOS PARA EL HOGAR' ,
            'ARTICULOS RELIGIOSOS' ,
            'ARTICULOS Y ACCESORIOS MILITARES' ,
            'ARTIFICIOS PIROTECNICOS' ,
            'ARTISTAS, ESCRITORES Y TECNICOS INDEPENDIENTES' ,
            'ASESORIA EN INVERSIONES' ,
            'ASILO' ,
            'ASOCIACIONES Y ORGANIZACIONES CIVILES' ,
            'AUTO ABASTO DE COMBUSTIBLE' ,
            'AUTO BAÑOS' ,
            'AUTOCINEMAS' ,
            'BALNEARIO' ,
            'BAÑOS PUBLICOS' ,
            'BANQUETES' ,
            'BAR' ,
            'BAR EN CABARET' ,
            'BAR EN CENTRO NOCTURNO' ,
            'BAR EN CLUB, CENTROS RECREATIVOS' ,
            'BAR EN DISCOTEQUE' ,
            'BAR EN HOTEL' ,
            'BAR EN MOTEL' ,
            'BAR EN MOTORHOTEL' ,
            'BAR EN RESTAURANTE' ,
            'BASCULA' ,
            'BAZAR' ,
            'BEBIDAS DE ALTA GRADUACIÓN ANEXO ABARROTES' ,
            'BEBIDAS SIN CONTENIDO ALCOHOLICO' ,
            'BICICLETAS' ,
            'BILLAR CATEGORIA A' ,
            'BILLAR CATEGORIA B CON VENTA DE BEBIDAS DE BAJA GRADUACION' ,
            'BILLAR CATEGORIA C' ,
            'BILLETES DE LOTERÍA' ,
            'BISUTERIA' ,
            'BLANCOS' ,
            'BODEGA' ,
            'BODEGA (EXCLUSIVA PARA ANEXO)' ,
            'BODEGA DE ACOPIO Y RECICLAJE DE RESIDUOS DIVERSOS' ,
            'BOLERAMA' ,
            'BOLERIA' ,
            'BONETERIA Y MERCERÍA' ,
            'BOTANAS' ,
            'BUFETES JURIDICOS' ,
            'CABARET' ,
            'CAFE' ,
            'CAFETERIA' ,
            'CAJA POPULAR' ,
            'CAJAS DE CARTON, MATERIAL DE EMPAQUE' ,
            'CAJAS DE SEGURIDAD' ,
            'CAMARA DE REFRIGERACION' ,
            'CAMPISMO' ,
            'CAMPOS DE GOLF' ,
            'CANCHAS DEPORTIVAS' ,
            'CANTINA' ,
            'CARBON Y LEÑA' ,
            'CARNE EMPACADA' ,
            'CARNES FRIAS' ,
            'CARNICERIA' ,
            'CARNITAS Y CHICHARRÓN' ,
            'CARPINTERIA' ,
            'CASA DE BOLSA' ,
            'CASA DE CAMBIO' ,
            'CASA DE HUESPEDES' ,
            'CASA HOGAR (ORFANATORIO)' ,
            'CEMENTERIO' ,
            'CENTRO ARTISTICO Y CULTURAL' ,
            'CENTRO DE ACOPIO' ,
            'CENTRO DE COPIADO' ,
            'CENTRO DE DISTRIBUCION DE MASA Y TORTILLA' ,
            'CENTRO DE ESPECTACULOS' ,
            'CENTRO NOCTURNO' ,
            'CENTRO TERAPEUTICO' ,
            'CENTRO TURISTICO' ,
            'CENTROS BOTANEROS' ,
            'CEREALES Y SEMILLAS' ,
            'CERRAJERIA' ,
            'CHATARRA Y RECICLADOS' ,
            'CLASES DE CORTE Y CONFECCION' ,
            'CLASES DE MANUALIDADES' ,
            'CLASES DE REGULARIZACION' ,
            'CLINICA' ,
            'CLINICA DE BELLEZA' ,
            'CLINICA VETERINARIA' ,
            'CLUB CINEGETICO' ,
            'CLUB DEPORTIVO SOCIAL' ,
            'CLUB SOCIAL' ,
            'COCINA ECONOMICA' ,
            'COCINA ECONOMICA' ,
            'COMECIO AL POR MAYOR DE EVISTAS Y PERIODICOS' ,
            'COMECIO AL POR MAYOR DE JUGUETES Y BICICLETAS' ,
            'COMERCIA AL POR MAYOR DE ARTICULOS DE PAPELERIA' ,
            'COMERCIO A POR MAYOR DE CALZADO' ,
            'COMERCIO AL POR MAYOR DE ARTICULOS DE JOYERIA Y RELOJES' ,
            'COMERCIO AL POR MAYOR DE ARTICULOS DESECHABLES' ,
            'COMERCIO AL POR MAYOR DE BLANCOS' ,
            'COMERCIO AL POR MAYOR DE CEMENTO, TABIQUE Y GRAVA' ,
            'COMERCIO AL POR MAYOR DE CUEROS Y PIELES' ,
            'COMERCIO AL POR MAYOR DE DISCOS Y CASETES' ,
            'COMERCIO AL POR MAYOR DE FIBRAS, HILOS Y TELAS' ,
            'COMERCIO AL POR MAYOR DE LIBROS' ,
            'COMERCIO AL POR MAYOR DE PINTURA' ,
            'COMERCIO AL POR MAYOR DE ROPA, ACCESORIOS, BISUTERIA Y ACC.DE VESTIR' ,
            'COMERCIO AL POR MAYOR DE VIDRIOS Y ESPEJOS' ,
            'COMPRA VENTA' ,
            'COMPRA VENTA AL POR MAYOR DE MOBILIARIO, EQUIPO E INSTRUMENTAL MEDICO' ,
            'COMPRA VENTA CERRADURAS INTELIGENTES Y CAJAS FUERTES' ,
            'COMPRA VENTA DE SISTEMA DE COMPUTO Y CONSUMIBLES' ,
            'COMPRA Y VENTA DE LLANTAS' ,
            'CONSERVADOR DE PRODUCTOS HELADOS' ,
            'CONSERVAS ALIMENTICIAS' ,
            'CONSULTORIO MEDICO' ,
            'CONSULTORIO ODONTOLOGICO' ,
            'CONSULTORIOS' ,
            'CONSUMIBLES PARA FILMACIONES' ,
            'CORTIJO TAURINO' ,
            'CREMERIA' ,
            'CRISTALERIA' ,
            'CULTIVO DE AGAVES ALCOHOLEROS' ,
            'CULTIVO DE JITOMATE O TOMATE ROJO' ,
            'CULTIVO DE MAIZ FORRAJERO' ,
            'CULTIVO DE MAIZ GRANO' ,
            'CULTIVO DE SORGO GRANO' ,
            'DEMOSTRACIONES' ,
            'DEPILACION CON CERA' ,
            'DEPILACIONES' ,
            'DEPORTES EXTREMOS' ,
            'DEPORTISTAS PROFESIONALES' ,
            'DEPORTIVOS Y SIMILARES QUE CUENTAN CON INSTALACIONES PARA PRESENTARLOS' ,
            'DESECHABLES' ,
            'DESPACHOS DE INVESTIGACION DE SOLVENCIA ECONOMICA' ,
            'DETALLADO AUTOMOTRIZ' ,
            'DISCOTEQUES' ,
            'DISEÑO DE ANUNCIOS A MANO Y POR COMPUTADORA' ,
            'DISEÑO DE ANUNCIOS, ROTULOS, LONAS Y TOLDOS LUMINOSOS' ,
            'DISEÑO E IMPRESION' ,
            'DISTRIBUCION DE PELICULAS Y AUDIOVISUALES' ,
            'DULCERIA' ,
            'EDICION DE DIRECTORIOS Y DE LISTAS DE CORREO' ,
            'EDICION DE LIBROS' ,
            'EDICION DE LIBROS INTEGRADA CON LA IMPRESION' ,
            'EDICION DE PERIODICOS' ,
            'EDICION DE PERIODICOS INTEGRADA CON LA IMPRESION' ,
            'EDICION DE REVISTAS Y OTRAS PUBLICACIONES PERIODICAS' ,
            'EDUCACION INICIAL' ,
            'ELABORACION DE COMPOSTA' ,
            'ELABORACIÓN DE PRODUCTOS HELADOS' ,
            'ELABORACION DE VINOS Y LICORES' ,
            'ELEVADORES' ,
            'EMBOBINADO Y REPARACION DE MOTORES ELECTRICOS Y ELECTRONICOS' ,
            'EMPAQUES EN GENERAL' ,
            'EQUIPO' ,
            'EQUIPO DE ILUMINACION' ,
            'EQUIPO MEDICO' ,
            'ESCALERA ELECTRICA' ,
            'ESCUELA' ,
            'ESCUELA DE ESTUDIOS SUPERIORES' ,
            'ESCUELA DE LICENCIATURA' ,
            'ESCUELA PREESCOLAR' ,
            'ESCUELA PREPARATORIA' ,
            'ESCUELA PRIMARIA' ,
            'ESCUELA SECUNDARIA' ,
            'ESPACIOS RECREATIVOS' ,
            'ESTACION DE GAS' ,
            'ESTACION DE GASOLINA' ,
            'ESTACIONAMIENTO' ,
            'ESTACIONAMIENTO EN CENTRO COMERCIAL' ,
            'ESTACIONAMIENTO PUBLICO' ,
            'ESTADIOS' ,
            'ESTANCIA INFANTIL' ,
            'ESTETICA' ,
            'ESTIMULACION TEMPRANA' ,
            'ESTUDIOS CINEMATOGRAFICOS' ,
            'ESTUDIOS FOTOGRAFICOS' ,
            'EVENTOS Y ESPECTACULOS' ,
            'EXP. DE AGUA PURIFICADA' ,
            'EXP. DE POLLO' ,
            'EXPENDIO DE BEBIDAS ALCOHOLICAS DE CUALQUIER TIPO' ,
            'EXPENDIO DE BEBIDAS DE BAJA GRADUACION EN B.C.' ,
            'EXPENDIO EN ENVASE CERRADO DE ALCOHOL PARA USO MEDICO' ,
            'FABRICA DE MATERIALES PARA LA CONSTRUCCIÓN' ,
            'FABRICAS E INDUSTRIAS' ,
            'FARMACIA' ,
            'FERRETERIA' ,
            'FERTILIZANTES' ,
            'FLORERIA' ,
            'FLORICULTURA EN INVERNADEROS Y OTRAS ESTRUCTURAS AGRICOLAS PROTEGIDAS' ,
            'FONDA' ,
            'FOTOCOPIADORA' ,
            'FRUTAS Y VERDURAS' ,
            'FUENTE DE SODAS' ,
            'GALERIA DE ARTE' ,
            'GIMNASIO' ,
            'GRABACIONES DE AUDIO Y VIDEO' ,
            'GRANJA' ,
            'GUARDERIAS' ,
            'HELICICULTURA' ,
            'HERRERIA' ,
            'HORNO CREMATORIO' ,
            'HORNO CREMATORIO PARA MASCOTAS' ,
            'HOSPITALES Y CLINICAS' ,
            'HOTEL' ,
            'HUESARIO' ,
            'HUEVO' ,
            'IMPRENTA' ,
            'IMPRESION' ,
            'INCINERADOR DE DESECHOS' ,
            'INCUBADORA' ,
            'INDUSTRIALES' ,
            'INMOBILIARIA' ,
            'INMOBILIARIAS Y CORREDORES DE BIENES RAICES' ,
            'INST. BANCARIA Y DE CDTO.' ,
            'INST. DE EQUIPO DE SONIDO' ,
            'INSTALACION DE ACCESORIOS AUTOMOTRICES' ,
            'JOYERIA' ,
            'JUEGOS DE VIDEO' ,
            'JUEGOS MECANICOS Y ELECTROMECANICOS' ,
            'JUGUETERIA' ,
            'LAB. DE ANALISIS CLINICOS' ,
            'LAB. FOTOGRAFICO' ,
            'LABORATORIO' ,
            'LABORATORIO DE AUDIOVISUALES' ,
            'LABORATORIO DENTAL' ,
            'LABRADO Y CORTE ARTESANAL DE CANTERA' ,
            'LAVADEROS PUBLICOS' ,
            'LAVANDERIA' ,
            'LECHERIA' ,
            'LENCERIA' ,
            'LIBRERIAS' ,
            'LLANTERA' ,
            'LUDOTECA' ,
            'MADERERIA' ,
            'MANUALIDADES' ,
            'MANUFACTURA DOMICILIARIA' ,
            'MANUFACTURA MENOR' ,
            'MAQUILA' ,
            'MAQUINARIA EN GENERAL' ,
            'MAQUINAS TORTILLADORAS' ,
            'MAQUINAS TRAGAMONEDAS' ,
            'MARCOS Y MOLDURAS' ,
            'MARISCOS EN ESTADO NATURAL' ,
            'MARISCOS PROCESADOS PARA CONSUMO HUMANO' ,
            'MASA Y TORTILLAS' ,
            'MASAJES TERAPEUTICOS' ,
            'MATERIA PRIMA' ,
            'MATERIAL DISCOGRAFICO' ,
            'MATERIAL ELECTRICO' ,
            'MATERIALES DE CONSTRUCCION' ,
            'MESA DE BILLAR' ,
            'MESA DE JUEGO' ,
            'MINI RESTAURANTE BAR' ,
            'MINI SUSHI BAR' ,
            'MINI-SUPER' ,
            'MISCELANEA' ,
            'MOLINO DE NIXTAMAL' ,
            'MOTEL' ,
            'MOTOR HOTEL' ,
            'MUEBLERIAS' ,
            'MUSEO' ,
            'MUSEOS DEL SECTOR PRIVADO' ,
            'MUSICA EN VIVO' ,
            'MUSICOS Y CANCIONEROS' ,
            'NACION' ,
            'NEVERIA' ,
            'NOTARIAS PUBLICAS' ,
            'OBRADOR' ,
            'OFICINA ADMINISTRATIVA' ,
            'OFICINA CORPORATIVA' ,
            'OFICINA VIRTUAL' ,
            'OPTICA' ,
            'OTROS SERVICIOS DE CONSULTORIA CIENTIFICA Y TECNICA' ,
            'OTROS SERVICIOS DE LIMPIEZA' ,
            'OTROS SERVICIOS RELACIONADOS CON LA CONTABILIDAD' ,
            'PAILERIA' ,
            'PALENQUE' ,
            'PALETERIA' ,
            'PAN' ,
            'PANADERIA' ,
            'PAÑALES' ,
            'PAÑALES' ,
            'PANTALLA LUMINOSA' ,
            'PAPELERIA' ,
            'PARQUE ECOLOGICO' ,
            'PASTELERIA Y POSTRES' ,
            'PEDICURISTA' ,
            'PELETERIA' ,
            'PENSION CANINA' ,
            'PENSIONES DE AUTOS' ,
            'PERFUMERIA' ,
            'PETROLEO' ,
            'PINTURAS' ,
            'PISOS' ,
            'PISOS, AZULEJOS Y ACCESORIOS PARA BAÑO' ,
            'PISTA DE PATINAJE (HIELO)' ,
            'PISTA PARA MINI AUTOS ELECTRICOS' ,
            'PISTAS DE ACTIVIDADES DEPORTIVAS Y DE ESPARCIMIENTO' ,
            'PLANCHADURÍA' ,
            'PLASTICOS' ,
            'PODOLOGIA' ,
            'PRELICENCIA' ,
            'PRESTACION DE SERVICIOS' ,
            'PRESTADORES DE SERVICIOS' ,
            'PRESTAMOS' ,
            'PRESTAMOS PRENDARIOS' ,
            'PRODUCCION DE BEBIDAS ALCOHÓLICAS CON VENTA AL MENUDEO' ,
            'PRODUCTOS AGROPECUARIOS' ,
            'PRODUCTOS DE REPOSTERIA' ,
            'PRODUCTOS LACTEOS' ,
            'PRODUCTOS NATURISTAS' ,
            'PRODUCTOS QUIMICOS' ,
            'PRODUCTOS QUIMICOS DE LIMPIEZA' ,
            'PRONOSTICOS DEPORTIVOS' ,
            'PRONOSTICOS DEPORTIVOS' ,
            'PUERTAS Y VENTANAS' ,
            'PULQUERIA' ,
            'PURIFICACIÓN Y ENVASADO DE AGUA PARA CONSUMO HUMANO' ,
            'RADIODIFUSORA' ,
            'RASTRO' ,
            'RASTRO DE AVES (GIRO RESTRINGIDO)' ,
            'RECEPCION Y ENTREGA DE ROPA PARA TINTORERIA' ,
            'REFACCIONARIA' ,
            'REGALOS' ,
            'RELACIONADOS' ,
            'RELLENO SANITARIO TECNIFICADO' ,
            'RELOJERIA' ,
            'RENTA DE AUTOMOTORES' ,
            'RENTA DE CANCHAS' ,
            'RENTA DE MOBILIARIO Y ARTICULOS PARA FIESTA' ,
            'RENTA DE SISTEMA DE COMPUTO' ,
            'REPARACION DE PARTES MECANICAS E HIDRAULICAS' ,
            'REPARACION DE ROPA' ,
            'REST-BAR CAMP.C/MUS.VIV PIST B' ,
            'REST-BAR CAMPESTRE CON MUSICA VIVO' ,
            'RESTAURANT- BAR CAMPESTRE,FOLKLORICO CON MUSICA EN VIVO' ,
            'RESTAURANTE' ,
            'RESTAURANTE BAR' ,
            'RESTAURANTE CON VENTA Y CONSUMO DE BEBIDAS DE BAJA GRADUACION' ,
            'RESTAURANTE-BAR CAMPESTRE' ,
            'RESTAURANTE-BAR FOLCKLORICO' ,
            'REVISTAS, LIBROS Y PERIODICOS' ,
            'ROCKOLA EVENTUAL' ,
            'ROPA' ,
            'ROPA DE BEBE' ,
            'ROSTICERIA' ,
            'ROTULISTAS' ,
            'ROTULOS' ,
            'SABANAS Y COLCHAS' ,
            'SALA DE EXHIBICION' ,
            'SALAS CINEMATOGRAFICAS' ,
            'SALON CON MUSICA V. Y PISTA BAILE' ,
            'SALON DE BAILE' ,
            'SALON DE EVENTOS' ,
            'SALON DE EVENTOS CON MUSICA EN VIVO' ,
            'SALON DE EVENTOS CON PISTA DE BAILE' ,
            'SALON DE FIESTAS INFANTILES' ,
            'SALON DE JUEGOS (EXCLUSIVO ANEXO)' ,
            'SALON DE MASAJES' ,
            'SASTRERIA' ,
            'SERVI-BAR DE CUATRO A GRAN TURISMO' ,
            'SERVI-BAR DE UNA A TRES ESTRELLAS' ,
            'SERVICIO DE COMEDOR PARA EMPRESAS' ,
            'SERVICIOS AUTOMOTRICES' ,
            'SERVICIOS FUNERARIOS' ,
            'SILLON PARA MASAJES' ,
            'SOLVENTES' ,
            'TABAQUERIA' ,
            'TALABARTERIA' ,
            'TALLER' ,
            'TALLER AUTOELECTRICO' ,
            'TALLER DE APARATOS ELECTRODOMESTICOS' ,
            'TALLER DE APARATOS ELECTRONICOS Y ELECTRICOS' ,
            'TALLER DE BICICLETAS' ,
            'TALLER DE CALZADO' ,
            'TALLER DE CERAMICA' ,
            'TALLER DE COSTURA' ,
            'TALLER DE JOYERIA' ,
            'TALLER DE LAMINADO Y PINTURA' ,
            'TALLER DE MOFLES' ,
            'TALLER DE MOTOS' ,
            'TALLER DE SOLDADURA' ,
            'TALLER DE TORNO' ,
            'TALLER MECANICO' ,
            'TAPICERÍA' ,
            'TARJETAS Y ACCESORIOS TELEFONICOS' ,
            'TATUAJES Y PERFORACIONES' ,
            'TEATRO' ,
            'TELAS' ,
            'TELEFONOS CELULARES' ,
            'TELEFONOS Y FAX PUBLICO' ,
            'TELEVISION POR CABLE' ,
            'TERMINAL DE AUTOBUSES' ,
            'TERRAZA (EXCLUSIVA PARA ANEXO)' ,
            'TERRAZA CAMPESTRE' ,
            'TERRAZA CAMPESTRE CON MUSICA EN VIVO' ,
            'TERRAZA CAMPESTRE CON MUSICA VIVO Y PISTA BAILE' ,
            'TERRAZA SIN VENTA Y O CONSUMO DE BEBIDAS ALCOHOLICAS' ,
            'TERRAZA TIPO A' ,
            'TERRAZA TIPO B' ,
            'TIANGUIS DEL AUTOMOVIL' ,
            'TIENDA DE AUTOSERVICIO' ,
            'TIENDA DE DEPORTES' ,
            'TIENDA DEPARTAMENTAL' ,
            'TINTORERIA' ,
            'TLAPALERIA' ,
            'TOSTADERIA' ,
            'TOSTADERIA (VENTA)' ,
            'TRAILER PARK' ,
            'TRAILER PARK' ,
            'TRANSFORMACION DE ALIMENTOS' ,
            'VALET PARKING' ,
            'VENTA BEBIDAS DE BAJA GRADUACION EN B.C.' ,
            'VENTA DE ALIMENTOS' ,
            'VENTA DE ARTICULOS EROTICOS-SEXUALES (SEX SHOP)' ,
            'VENTA DE ATAUDES' ,
            'VENTA DE BEBIDAS DE BAJA GRADUACION' ,
            'VENTA DE BEBIDAS DE BAJA GRADUACION ANEXO A ABARROTES Y MISCELANEAS' ,
            'VENTA DE BEBIDAS DE BAJA GRADUACION ANEXO A MINI-SUPER' ,
            'VENTA DE BEBIDAS DE BAJA GRADUACION DEPOSITO' ,
            'VENTA DE BOLETOS' ,
            'VENTA DE CARTUCHOS PARA TIRO DEPORTIVO Y CACERIA' ,
            'VENTA DE DISFRACES VESTIMENTA REGIONAL Y VESTIDOS DE NOVIA' ,
            'VENTA DE HERRAJES EN GENERAL' ,
            'VENTA DE HIELO' ,
            'VENTA DE JUEGOS DE VIDEO' ,
            'VENTA DE SOMBREROS' ,
            'VENTA Y CONSUMO DE BEBIDAS DE BAJA GRADUACION ANEXO A RESTAURANTE' ,
            'VENTA Y CONSUMO DE BEBIDAS DE BAJA GRADUACION ANEXO A ALIMENTOS' ,
            'VENTA Y CONSUMO DE BEBIDAS DE BAJA GRADUACION ANEXO A CENTRO BOTANERO' ,
            'VENTA Y CONSUMO DE BEBIDAS DE BAJA GRADUACION ANEXO A ESTADIOS' ,
            'VENTA Y CONSUMO DE BEBIDAS DE BAJA GRADUACION ANEXO BILLARES O BOLICHE' ,
            'VENTA Y CONSUMO DE BEBIDAS DE BAJA GRADUACION ANEXO CANCHAS DEPORTIVAS' ,
            'VENTA Y CONSUMO DE BEBIDAS DE BAJA GRADUACION CON ALIMENTOS' ,
            'VETERINARIA' ,
            'VIDEO CLUB' ,
            'VIDEO-BAR' ,
            'VIDRIERA' ,
            'VINOS GENEROSOS EN B.A' ,
            'VINOS GENEROSOS EN B.C.' ,
            'VINOS Y LICORES EN ABARROTES' ,
            'VINOS Y LICORES EN MINI-SUPER' ,
            'VINOS Y LICORES EN TIENDAS DE AUTOSERVICIO Y SUPERMERCADOS' ,
            'VINOS Y LICORES EN VINATERIAS' ,
            'VINOS Y LICORES P/CAFE' ,
            'VIVERO' ,
            'VIVERO SIN PRODUCCION DE PLANTA' ,
            'VTA DE BEBIDAS DE BAJA GRAD. EN TIENDA DE AUTOSERVICIO Y SUPERMERCADOS' ,
            'YOGA' ,
            'ZAPATERIA' ,
        ];
    }
    public function getCities(){
        return [
            'Acapulco' ,
            'Aguascalientes' ,
            'Apodaca' ,
            'Buenavista' ,
            'Campeche' ,
            'Cancún' ,
            'Celaya' ,
            'Chalco' ,
            'Chetumal' ,
            'Chicoloapan' ,
            'Chihuahua' ,
            'Chilpancingo' ,
            'Chimalhuacán' ,
            'Ciudad Acuña' ,
            'Ciudad de México DF (CDMX)' ,
            'Ciudad del Carmen' ,
            'Ciudad López Mateos' ,
            'Ciudad Madero' ,
            'Ciudad Obregón' ,
            'Ciudad Valles' ,
            'Ciudad Victoria' ,
            'Coatzacoalcos' ,
            'Colima' ,
            'Córdoba' ,
            'Cuauhtémoc' ,
            'Cuautitlán' ,
            'Cuautitlán Izcalli' ,
            'Cuautla' ,
            'Cuernavaca' ,
            'Culiacán' ,
            'Delicias' ,
            'Durango' ,
            'Ecatepec' ,
            'Ensenada' ,
            'Fresnillo' ,
            'General Escobedo' ,
            'Gómez Palacio' ,
            'Guadalajara' ,
            'Guadalupe' ,
            'Guaymas' ,
            'Hermosillo' ,
            'Hidalgo del Parral' ,
            'Iguala' ,
            'Irapuato' ,
            'Ixtapaluca' ,
            'Jiutepec' ,
            'Juárez' ,
            'La Paz' ,
            'León' ,
            'Los Cabos (San José y Cabo San Lucas)' ,
            'Los Mochis' ,
            'Mahahual' ,
            'Manzanillo' ,
            'Matamoros' ,
            'Mazatlán' ,
            'Mérida' ,
            'Mexicali' ,
            'Minatitlán' ,
            'Miramar' ,
            'Monclova' ,
            'Monterrey' ,
            'Morelia' ,
            'Naucalpan' ,
            'Naucalpan de Juárez' ,
            'Navojoa' ,
            'Nezahualcóyotl' ,
            'Nogales' ,
            'Nuevo Laredo' ,
            'Oaxaca de Juárez' ,
            'Ojo de Agua' ,
            'Orizaba' ,
            'Pachuca' ,
            'Piedras Negras' ,
            'Playa del Carmen' ,
            'Poza Rica de Hidalgo' ,
            'Puebla' ,
            'Puerto Vallarta' ,
            'Querétaro' ,
            'Reynosa' ,
            'Salamanca' ,
            'Saltillo' ,
            'San Cristóbal de las Casas' ,
            'San Francisco Coacalco' ,
            'San Juan Bautista Tuxtepec' ,
            'San Juan del Río' ,
            'San Luis Potosí' ,
            'San Luis Río Colorado' ,
            'San Miguel de Allende' ,
            'San Nicolás de los Garza' ,
            'San Pablo de las Salinas' ,
            'San Pedro Garza García' ,
            'Santa Catarina' ,
            'Soledad de Graciano Sánchez' ,
            'Tampico' ,
            'Tapachula' ,
            'Taxco' ,
            'Tehuacán' ,
            'Tepexpan' ,
            'Tepic' ,
            'Texcoco de Mora' ,
            'Tijuana' ,
            'Tlalnepantla' ,
            'Tlaquepaque' ,
            'Toluca' ,
            'Tonalá' ,
            'Torreón' ,
            'Tulancingo de Bravo' ,
            'Tuxtla' ,
            'Uruapan' ,
            'Veracruz' ,
            'Villa de Álvarez' ,
            'Villa Nicolás Romero' ,
            'Villahermosa' ,
            'Xalapa Enriquez' ,
            'Xico' ,
            'Zacatecas' ,
            'Zamora' ,
            'Zapopan' ,
        ];
    }
}
